[package]
name = "find-dup-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
homedir = "0.2.1"
rfd = "0.14.1"
magnetic = "2.4.1"
maplit = "1.0.2"
num_cpus = "1.16.0"
walkdir = "2.5.0"

# New versions don't work with img_hash
image = "0.19"
egui_extras = "0.27.2"

[dependencies.img_hash]
version = "2.1.0"
# For interop with `image`:
features = ["rust-image"]
